INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CUSTOM_BLOCKS custom_blocks)

FIND_PATH(
    CUSTOM_BLOCKS_INCLUDE_DIRS
    NAMES custom_blocks/api.h
    HINTS $ENV{CUSTOM_BLOCKS_DIR}/include
        ${PC_CUSTOM_BLOCKS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CUSTOM_BLOCKS_LIBRARIES
    NAMES gnuradio-custom_blocks
    HINTS $ENV{CUSTOM_BLOCKS_DIR}/lib
        ${PC_CUSTOM_BLOCKS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CUSTOM_BLOCKS DEFAULT_MSG CUSTOM_BLOCKS_LIBRARIES CUSTOM_BLOCKS_INCLUDE_DIRS)
MARK_AS_ADVANCED(CUSTOM_BLOCKS_LIBRARIES CUSTOM_BLOCKS_INCLUDE_DIRS)

